'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {money,metrics,missing,type Practice} from '../lib/model';
import {measures} from '../lib/reference';
export default function Editor({practice,version,onClose,onSave}:{practice:Practice;version:number;onClose:()=>void;onSave:(p:Practice,v:number)=>Promise<void>}){
 const [p,setP]=useState(practice),[tab,setTab]=useState('Pratica'),[busy,setBusy]=useState(false),[error,setError]=useState('');const m=metrics(p);
 const field=(key:keyof Practice,label:string,type='text',locked=false)=>{const numeric=['power','storage','quantity','probability','commissionRate'].includes(key);const monetary=['amount','cost'].includes(key);const value=p[key];return <label className="field" key={key}>{label}<input type={type} step={type==='number'?'any':undefined} disabled={locked} value={value==null?'':monetary?Number(value)/100:String(value)} onChange={e=>setP({...p,[key]:numeric||monetary?e.target.value===''?null:Math.round(Number(e.target.value)*(monetary?100:1000))/(monetary?1:1000):e.target.value})}/></label>};
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="editor-modal"><DialogHeader><DialogTitle>{p.name||'Nuova pratica'}</DialogTitle><DialogDescription>{p.source} · {p.row?`Riga Excel ${p.row}`:'Previsione commerciale'}</DialogDescription></DialogHeader><div className="tabs">{['Pratica','Impianto','Economia'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave(p,version);onClose()}catch(e){setError(e instanceof Error?e.message:'Salvataggio non riuscito')}finally{setBusy(false)}}}>
 {tab==='Pratica'&&<div className="form-grid">{field('name','Nome cliente / pratica')}{field('agent','Agente · fonte Leadora / storico')}{field('state','Fase commerciale')}<label className="field">Misura<select value={p.measure} onChange={e=>setP({...p,measure:e.target.value})}><option value="">Da completare</option>{[...new Set([...measures,p.measure])].filter(Boolean).map(x=><option key={x}>{x}</option>)}</select></label>{field('customerCode','Codice cliente')}{field('contractCode','Codice contratto ENERP')}{field('customerType','Tipologia cliente')}{field('partner','Partner tecnico')}<label className="field wide">Descrizione · fonte Leadora / storico<textarea rows={3} value={p.description} onChange={e=>setP({...p,description:e.target.value})}/></label></div>}
 {tab==='Impianto'&&<div className="form-grid">{field('list','Listino')}{field('quantity','Numero impianti','number')}{field('power','Potenza impianto · kW','number')}{field('storage','Accumulo · kWh','number')}{field('panel','Pannelli · marca e modello')}{field('battery','Accumulo · marca e modello')}</div>}
 {tab==='Economia'&&<><div className="notice">{'I valori importati restano modificabili. Previsione ponderata. Costo suggerito: 80% se non indicato. Fatturazione prevista: chiusura + 35 giorni. Valuta di lavoro: EUR; base IVA da confermare.'}</div><div className="form-grid">{field('amount','Importo nominale · â‚¬','number')}{field('probability','ProbabilitÃ  di chiusura · %','number')}{field('closeDate','Data contrattualizzazione / prevista','date')}{field('marginDate','Data attribuzione margine','date')}{field('cost','Costo · â‚¬ (vuoto: stima 80%)','number')}{field('commissionRate','Provvigione · %','number')}{field('taxable','Imponibile · €','number')}{field('secondMarginPercent','% II margine','number')}{field('taxable','Imponibile · €','number')}{field('secondMarginPercent','% II margine','number')}</div><div className="mini-metrics"><div>Valore ponderato<strong>{money(m.contract)}</strong></div><div>Primo margine<strong>{money(m.margin)}</strong></div><div>Secondo margine<strong>{money(m.secondMargin)}</strong></div></div></>}
 {missing(p).length>0&&<details className="review"><summary>{missing(p).length} informazioni da completare o verificare</summary><ul>{missing(p).map(x=><li key={x}>{x}</li>)}</ul></details>}{error&&<p role="alert" className="error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose} disabled={busy}>Annulla</button><button className="primary" disabled={busy}>{busy?'Salvataggioâ€¦':'Salva pratica'}</button></div></form></DialogContent></Dialog>
}
