'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {money,metrics,missing,type Practice,type Invoice} from '../lib/model';
import {measures} from '../lib/reference';
export default function Editor({practice,version,invoices=[],onClose,onSave,onDelete}:{practice:Practice;version:number;invoices?:Invoice[];onClose:()=>void;onSave:(p:Practice,v:number)=>Promise<void>;onDelete?:(p:Practice)=>Promise<void>}){
 const contractDescription=(value:string)=>{const code=value.trim();if(!code)return '';const normalized=code.replace(/^CONN-/i,'');const parts=normalized.split('-');return parts.length>1?parts.slice(0,-1).join('-'):normalized};
 const [p,setP]=useState(()=>({...practice,description:practice.description||contractDescription(practice.contractCode||'')})),[tab,setTab]=useState('Pratica'),[busy,setBusy]=useState(false),[error,setError]=useState('');const m=metrics(p);
 useEffect(()=>{if(p.probability!=null){const kind=p.probability===100?'R':'S';if(p.kind!==kind)setP(current=>({...current,kind}))}},[p.probability,p.kind]);
 const field=(key:keyof Practice,label:string,type='text',locked=false)=>{const numeric=['power','storage','quantity','probability','commissionRate'].includes(key);const monetary=['amount','cost','taxable','commission'].includes(key);const value=key==='secondMarginPercent'&&p.secondMarginPercent==null&&p.taxable&&m.secondMargin!=null?Number((m.secondMargin/p.taxable*100).toFixed(4)):key==='commission'&&p.commission==null?m.commission:p[key];return <label className="field" key={key}>{label}<input type={type} step={type==='number'?'any':undefined} disabled={locked} value={value==null?'':monetary?Number(value)/100:String(value)} onChange={e=>setP({...p,[key]:numeric||monetary?e.target.value===''?null:Math.round(Number(e.target.value)*(monetary?100:1000))/(monetary?1:1000):e.target.value})}/></label>};
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="editor-modal"><DialogHeader><DialogTitle>{p.name||'Nuova pratica'}</DialogTitle><DialogDescription>{p.source} · {p.row?`Riga Excel ${p.row}`:'Previsione commerciale'}</DialogDescription></DialogHeader><div className="tabs">{['Pratica','Impianto','Economia'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave(p,version);onClose()}catch(e){setError(e instanceof Error?e.message:'Salvataggio non riuscito')}finally{setBusy(false)}}}>
 {tab==='Pratica'&&<div className="form-grid">{field('name','Nome cliente / pratica')}{field('agent','Agente · fonte Leadora / storico')}{field('state','Fase commerciale')}<label className="field">Stima / Reale<select value={p.kind} onChange={e=>setP({...p,kind:e.target.value as 'R'|'S'})}><option value="R">Reale</option><option value="S">Stimata</option></select></label><label className="field">Misura<select value={p.measure} onChange={e=>setP({...p,measure:e.target.value})}><option value="">Da completare</option>{[...new Set([...measures,p.measure])].filter(Boolean).map(x=><option key={x}>{x}</option>)}</select></label>{field('customerCode','Codice cliente')}<label className="field">Codice contratto ENERP<input value={p.contractCode||''} onChange={e=>{const contractCode=e.target.value;const generated=contractDescription(contractCode);setP({...p,contractCode,description:generated||p.description})}}/></label>{field('customerType','Tipologia cliente')}{field('partner','Partner tecnico')}<label className="field wide">Descrizione commessa<textarea rows={3} value={p.description} onChange={e=>setP({...p,description:e.target.value})}/></label></div>}
 {tab==='Impianto'&&<div className="form-grid">{field('list','Listino')}{field('quantity','Numero impianti','number')}{field('power','Potenza impianto · kW','number')}{field('storage','Accumulo · kWh','number')}{field('panel','Pannelli · marca e modello')}{field('battery','Accumulo · marca e modello')}</div>}
 {tab==='Economia'&&<><div className="notice">I valori importati restano modificabili. Importo contrattualizzato calcolato sulla probabilità. Costo suggerito: 80% se non indicato. Fatturazione prevista: chiusura + 35 giorni. Valuta di lavoro: EUR; base IVA da confermare.</div><div className="form-grid">{field('amount','Importo nominale · €','number')}{field('probability','Probabilità di chiusura · %','number')}{field('closeDate','Data contrattualizzazione / prevista','date')}{field('marginDate','Data attribuzione margine','date')}{field('cost','Costo · € (vuoto: stima 80%)','number')}{field('commissionRate','Provvigione · %','number')}{field('commission','Provvigioni · € (automatiche o manuali)','number')}{field('taxable','Imponibile · €','number')}{field('secondMarginPercent','% II margine','number')}</div><div className="mini-metrics"><div>Importo contrattualizzato<strong>{money(m.contract)}</strong></div><div>Primo margine<strong>{money(m.margin)}</strong></div><div>Secondo margine<strong>{money(m.secondMargin)}</strong></div></div><div className="linked-invoices"><div className="linked-invoices-head"><div><strong>Fatture collegate</strong><span>{invoices.length} documenti</span></div><strong>{money(invoices.reduce((total,i)=>total+i.total,0))}</strong></div>{invoices.length?<div className="linked-invoice-list">{invoices.map(i=><div key={i.id}><span><b>{i.number||'Senza numero'}</b><small>{i.date||'Data non indicata'} · {i.source}</small></span><strong>{money(i.total)}</strong></div>)}</div>:<p className="caption">Nessuna fattura collegata a questa pratica.</p>}</div></>}
 {missing(p).length>0&&<details className="review"><summary>{missing(p).length} informazioni da completare o verificare</summary><ul>{missing(p).map(x=><li key={x}>{x}</li>)}</ul></details>}{error&&<p role="alert" className="error">{error}</p>}<div className="modal-actions">{onDelete&&!p.id.startsWith('new:')&&<button type="button" className="secondary" onClick={async()=>{if(confirm('Eliminare questa pratica?')){setBusy(true);try{await onDelete(p);onClose()}catch(e){setError(e instanceof Error?e.message:'Eliminazione non riuscita')}finally{setBusy(false)}}}} disabled={busy}>Elimina pratica</button>}<button type="button" className="secondary" onClick={onClose} disabled={busy}>Annulla</button><button className="primary" disabled={busy}>{busy?'Salvataggioâ€¦':'Salva pratica'}</button></div></form></DialogContent></Dialog>
}




